### ISSUE TITLE
Content type

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/OctopusDeploy-Api#1]
Currently all of our resources are in JSON format, and I can't see a compelling reason to enable any other serialization format. We serve them up with the `application/json` MIME type. 

Should we be using a custom content type? For example:

```
application/vnd.octopusdeploy.2.0+json
```

Or should we use a custom type for every resource type?

```
application/vnd.octopusdeploy.environment.2.0+json
application/vnd.octopusdeploy.project.2.0+json
```

My only worry is that there might be practical implications to this approach; some environments might have funny IIS or proxy server configurations that make custom content types not work.

**Comment by droyad** [comment]
Doesn't seem to have come up, or any comments, so closing
