### ISSUE TITLE
Multiple Wildcards Support in GET operations

### ISSUE THREAD

**Issue by uchagani** [OctopusDeploy/OctopusDeploy-Api#10]
How can we use multiple wildcards via the API.  For example, I have a multiple environments called something along the lines of `AQA-1.0.3.5-Something-Clean`.  I can match all environments that start with `AQA` by passing in `AQA*`.  But if I want to only get environments that contain `Something` I can't use `*Something*`.  

Can someone clear up the wildcard usage?  Please and thanks.

**Comment by droyad** [comment]
Sorry, we were not monitoring this repository for questions. If you still have some, please contact [support](https://octopus.com/support).
