### ISSUE TITLE
-SkipHttpErrorCheck doesn't work in PowerShell 5.1

### ISSUE THREAD

**Issue by Caltor** [OctopusDeploy/OctopusDeploy-Api#100]
Line 81 of https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/67ce527d8d0b222f5d33fd51d04575cb14798610/REST/PowerShell/Feeds/SyncPackages.ps1 includes the -SkipHttpErrorCheck parameter. This doesn't work in PowerShell 5.1. According to https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7 this parameter seems to have appeared in PowerShell 7.0 (possibly 6 but that is out of support now and not documented). Could this script be made to work in version 5.1 please or include a check for the PowerShell version being used. The current message `A parameter cannot be found that matches parameter name 'SkipHttpErrorCheck'` is somewhat confusing.

**Comment by harrisonmeister** [comment]
Thanks for raising @Caltor - I think I've pushed a fix that should resolve this.
