### ISSUE TITLE
SyncPackages depends upon non-mandatory $PackageListFilePath parameter

### ISSUE THREAD

**Issue by Caltor** [OctopusDeploy/OctopusDeploy-Api#101]
If https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/67ce527d8d0b222f5d33fd51d04575cb14798610/REST/PowerShell/Feeds/SyncPackages.ps1 script is run without providing the $PackageListFilePath parameter then it fails with the following message:
`Cannot bind argument to parameter 'PackageListFilePath' because it is an empty string.`

Could you make this parameter mandatory please so the user gets prompted if they neglect to provide it. I can't see any documentation for this script so this is even more important to improve the user experience.

**Comment by harrisonmeister** [comment]
Thanks for raising @Caltor - fixed this just now :+1:
