### ISSUE TITLE
Async support in Octopus.Client

### ISSUE THREAD

**Issue by andywilsonuk** [OctopusDeploy/OctopusDeploy-Api#11]
Hi,

Do you have plans to support Async tasks? I'm calling the library from within ASP.net so it would be good to take advantage of thread parking whilst the HTTP request to the Octopus server is waiting for a response.

Cheers
Andy

**Comment by droyad** [comment]
We implemented this in `Octopus.Client` `4.0`, sorry about the delay in replies we were not monitoring this repo for issues.
