### ISSUE TITLE
Inconsistencies in repository-resource hierarchy

### ISSUE THREAD

**Issue by Suremaker** [OctopusDeploy/OctopusDeploy-Api#13]
Hello,

During usage of OctopusClient I found out a following inconsistencies:
- the ILifecyclesRepository interface does not extend IFindByName<LifecycleResource> interface even though LifecycleResource implements INamedResource,
- the LibraryVariableSetResource class does not implement INamedResource interface even though it has Name property (and ILibraryVariableSetRepository interface does not extend IFindByName<LibraryVariableSetResource>).

Would it be possible to add the missing interfaces to make the type hierarchy consistent and simplify usage of it?

Thanks!

**Comment by droyad** [comment]
Sorry, we were not monitoring this repo for issues, however this looks to have been resolved.
