### ISSUE TITLE
Octopus.Client Nupak is fixed to only support 4.5

### ISSUE THREAD

**Issue by mhsimkin** [OctopusDeploy/OctopusDeploy-Api#20]
The Octopus.Client nupak should not be fixed to .NET 4.5.  It should be set to require at least 4.5.

This will allow projects with 4.5.1, 4.5.2, 4.6, 4.6.1, and 4.6.2 to use the package.  I am only developing for 4.6.1 at this point as everything before 4.5.2 is not being supported by Microsoft at this point.

Thanks
marc

**Comment by droyad** [comment]
Sorry about the delay in replies, we have not been monitoring this repo. You can use 4.5 libraries from a 4.61 application.
