### ISSUE TITLE
Example POST /api/releases

### ISSUE THREAD

**Issue by enriqueescobar-askida** [OctopusDeploy/OctopusDeploy-Api#25]
what extra values I should pass into header to create a release?
Using X-Octopus-ApiKey i can even delete old release
but I do not know how to use X-ChannelId & X-ReleaseId

Thanks

**Comment by matt-richardson** [comment]
The only header that you need to use is `X-Octopus-ApiKey` - the rest of the values need to be supplied in the payload of the message. A good way to figure out what you need to send is to use the browser dev tools to watch what gets sent when you perform the action in the Octopus UI.

I've just pushed [an example script](https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/master/REST/PowerShell/Releases/CreateRelease.ps1) that shows how to create a release.

Hope that helps!
