### ISSUE TITLE
Do you have a licence?

### ISSUE THREAD

**Issue by klagan** [OctopusDeploy/OctopusDeploy-Api#29]
Does this library have a licence? @Dalmirog

**Comment by skyguy94** [comment]
https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/master/LICENSE.txt

**Comment by klagan** [comment]
Thanks for that. But i am silly.  And i posted this question under the wrong project :)  I was trying to ask OctoPosh.

**Comment by skyguy94** [comment]
It happens ;) 

More coffee....
