### ISSUE TITLE
Security Issue: User Role Permission 'VariableEdit' allows editing of 'UnscopedVariables' when User Role Permission of 'VariableEditUnscoped' is not selected

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/OctopusDeploy-Api#36]
**Octopus Version 4.0.2** 
(Able to replicated  on v3)

**Issue:**

Selecting "VariableEdit" within the User Role permissions will allow the associated Team and by extension User, to edit Unscoped Variables, despite having the permissions option for "UnscopedVariableEdit" unselected.

**Replication Steps:** 

1) Create a User Role via Configuration > User Roles, that contains the following permissions;

- EnvironmentView
- LibraryVariableSetEdit
- LibraryVariableSetView
- ProjectView
- VariableEdit
- VariableView
- VariableViewUnscoped

![image](https://user-images.githubusercontent.com/33012349/32929938-37d9916a-cba7-11e7-8f42-464eb2e1442a.png)

2) Create a Team via Configuration > Teams, that uses the newly created Role.

![image](https://user-images.githubusercontent.com/33012349/32929944-4890b966-cba7-11e7-9dbd-2c43c32a07af.png)

3) Create a User via Configuration > Users, that belongs to the newly created Team.

4) Log in as the newly created User

5) Navigate to an existing project that has Variables that are scoped and Variables that are unscoped.

![image](https://user-images.githubusercontent.com/33012349/32930034-cb4097d2-cba7-11e7-948d-45ad5b3c58f9.png)

6) You are able to Edit & Save Variables that are unscoped despite not having associated permissions. 

![image](https://user-images.githubusercontent.com/33012349/32930045-e5342d66-cba7-11e7-8324-c394d9e85413.png)

**Sources:**

https://help.octopusdeploy.com/discussions/problems/63487

**Comment by johnsimons** [comment]
This issue has been moved to https://github.com/OctopusDeploy/Issues/issues/3933
