### ISSUE TITLE
Don't leak persistence concerns out to your API

### ISSUE THREAD

**Issue by jbogard** [OctopusDeploy/OctopusDeploy-Api#4]
Looking at this:

https://github.com/OctopusDeploy/OctopusDeploy-Api/blob/master/sections/links.md#collections

You have an "IsStale" flag in the resource. This leaks the persistence technology to your API. I don't think I should care as a consumer that you use RavenDB or Mongo or Riak or PostgreSQL. Check out GitHub's collections. Here's what its issues look like:

http://developer.github.com/v3/issues/

Pure resources, without worrying about how exactly it's implemented behind the scenes. I'd suggest ditching the stale flag on the collection and the query altogether. If you want to indicate staleness, you can expose the collection's etag/timestamp.

Staleness would come from state affecting actions, PUT/POST/DELETE etc. If you want to support a PUT followed by a GET and have those two "agree" on consistency, there are other ways of doing so (write-through cache etc).

Another perspective is to ask why a developer using this API wouldn't want the most consistent option, since it's available? Just doing a warning won't really discourage anyone.

**Comment by droyad** [comment]
It is not used in 3.x, so removing in 4.x https://github.com/OctopusDeploy/Issues/issues/3658
