### ISSUE TITLE
How to get the user of a deployment?

### ISSUE THREAD

**Issue by nitrocode** [OctopusDeploy/OctopusDeploy-Api#41]
The deployment json doesn't contain the username. Any ideas on how to tie a deployment to a user?

**Comment by droyad** [comment]
@nitrocode You need to retrieve the `DeploymentQueued` event for the deployment.

in C#:
```
repository.Events.List(regarding: "Deployments-1234", eventCategories: "DeploymentQueued")
```

Direct url:
```
/api/events?regarding=Deployments-1234&eventCategories=DeploymentQueued
```
