### ISSUE TITLE
Querying for events by date does not allow you to specify positive UTC Offsets

### ISSUE THREAD

**Issue by fourpastmidnight** [OctopusDeploy/OctopusDeploy-Api#43]
I'm trying to use the Octopus ReST API directly from PowerShell.

I'm querying the Events repository, attempting to use a windowed query using the `from` and `to` parameters.

The following Uri allows me to successfully query the events, returning the expected number of items:

`api/events?regarding=SomeResourceId-1&from=2019-02-23T13:00:00.000-01:00&to=2019-02-24T13:00:00.000-01:00`

However, this does not work:

`api/events?regarding=SomeResourceId-1&from=2019-02-23T13:00:00.000+01:00&to=2019-02-24T13:00:00.000+01:00`

I get back many more items than I expect, with items occurring before the `from` date! I tried URL encoding the `+` symbol, but I get back the same result set as the unencoded URL above.

**Comment by matt-richardson** [comment]
Hi @fourpastmidnight - thanks for getting in touch.

I've just been doing some testing on this, and from what I can tell, as long as its encoded properly, it works fine?

When you're encoding, can you confirm you're getting something like this?
`api/events?regarding=SomeResourceId-1&from=2019-02-23T13%3A00%3A00.000%2B01%3A00&to=2019-02-24T13%3A00%3A00.000%2B01%3A00`

I think its almost definitely an encoding issue - the `+` will be decoded to a space, which will cause all sorts of havoc.

Let me know how you go.

ps - for questions like this, you'll get a faster response if you get in touch via one of our [support avenues](https://octopus.com/support). We dont always monitor git repos for issues like this.

**Comment by fourpastmidnight** [comment]
Hmm, then maybe I want encoding properly. Thanks for replying. I’ll give it another go.

Sent from my Windows 10 phone

**Comment by fourpastmidnight** [comment]
OK, I retested. I must have not encoded something correctly. This does work as expected. Thanks again.
