### ISSUE TITLE
New Resource - Roles

### ISSUE THREAD

**Issue by crossetj** [OctopusDeploy/OctopusDeploy-Api#5]
Roles tie servers, deployment steps, projects and releases together.

There have been many times when it would have been useful to me to see all the projects that deploy to a particular role. Or to find out what machines are in each role. To ensure environment coverage for a role.

Right now I can parse the machine records to figure out which machines are in a particular role. But to find what gets deployed to those machines I need to do a deep search through the /api/projects to find the steps.

The new API would at least expose the steps more easily. The deployment and releases resources might also have some useful information.

Roles are such  important linking pieces that they deserve to be a first level resource.

**Comment by droyad** [comment]
Sorry, but we were not monitoring this repo for issues. Thank you for the suggestion, and we have been considering that feature it for some time.
