### ISSUE TITLE
Documentation outdated for team API?

### ISSUE THREAD

**Issue by johnykes** [OctopusDeploy/OctopusDeploy-Api#53]
Hi!
I have a PowerShell script which is executed as a Process Step and its role is to create teams and link them to the desired project. Last year the script was working correctly, but now it doesn’t work anymore.

I see in your documentation that the teams resource has “ProjectIds” property, which I think is no more valid, because I get error when trying to populate this property and I also downloaded your repository from GitHub, searched for TeamResource and found out that this property is now in ScopedUserRoleResource class…

Context:
$endpoint = new-object -TypeName Octopus.Client.OctopusClient(New-Object 
Octopus.Client.OctopusServerEndpoint($OctopusParameters[’$OctopusURI’],$ApiKey))
$d = [ordered]@{
            "CanBeRenamed"=$true
            "CanChangeRoles"=$true
            "CanChangeMembers"=$true
            "Name" = $Teamname
            #ProjectIds - not working anymore... error, property does not exist.
        }
$newTeam= New-Object Octopus.Client.Model.TeamResource -Property $d;
$endpoint.post("/api/teams/", $newTeam, $null)

So, how should I now link the team to a project?
version 2018.9.10
Have a great day!

**Comment by johnykes** [comment]
:)

**Comment by harrisonmeister** [comment]
Hi @johnykes 

Sorry about the delay in responding. This repo isn't monitored.

If you are still having issues, then please get in touch at advice@octopus.com
