### ISSUE TITLE
Defect URI Is Giving 404

### ISSUE THREAD

**Issue by dapngn** [OctopusDeploy/OctopusDeploy-Api#6]
I receive a 404 when posting a resource defect to a valid resource id.

Application: "Octopus Deploy",
Version: "2.5.11.614",
ApiVersion: "3.0.0",

The following URI retrieves my release
GET /api/releases/releases-9999

But the following 404s
POST /api/releases/releases-9999/defects HTTP/1.1
X-Octopus-ApiKey: API-*
Description: "Some Test Description"

**Comment by droyad** [comment]
Sorry, but we were not monitoring this repo for issues. Hope you found the solution.
