### ISSUE TITLE
Add parameters to the Deployment process step

### ISSUE THREAD

**Issue by fauzankhanak** [OctopusDeploy/OctopusDeploy-Api#60]
How can I add parameters to my Process step using octopusDeploy-API powershell, i am able to create steps and add properties using"New-Object Octopus.Client.Model.DeploymentStepResource", "New-Object Octopus.Client.Model.DeploymentActionResource" respectively but i am not able to find the code to add the parameters to my step.

![Capture](https://user-images.githubusercontent.com/19772133/77229061-7a180780-6bb1-11ea-8af7-59633343f026.PNG)

**Comment by harrisonmeister** [comment]
Hi @fauzankhanak - Apologies for the delay, this repo isn't monitored.

If you are still facing issues, then please feel free to get in touch at advice@octopus.com

Thanks!
