### ISSUE TITLE
Is 'ReportDeploymentCountOverTimes' no longer available?

### ISSUE THREAD

**Issue by yooakim** [OctopusDeploy/OctopusDeploy-Api#8]
I'm writing a PowerShell module around the API and I can't seem to find the method [ReportDeploymentCountOverTimes](https://github.com/OctopusDeploy/OctopusDeploy-Api/wiki/ReportDeploymentCountOverTimes)

Is that no longer available?

**Comment by droyad** [comment]
Sorry, but we were not monitoring this repo for issues.

Looks like it's in the root document but does not work, we may need to remove it.

**Comment by droyad** [comment]
https://octopusdeploy.uservoice.com/ is a good place to add suggestions so that they come up on our radar

**Comment by droyad** [comment]
Closed in error earlier, along with the last (now deleted comment).

It looks like the API does exist, but there is no repository for it in Octopus.Clients. We will probably re-add it as part of 4.0, in the meantime, for future people who are looking for it, it can be accessed by using the client directly.
