### ISSUE TITLE
Is it possible to deploy on a single machine through API?

### ISSUE THREAD

**Issue by talien** [OctopusDeploy/OctopusDeploy-Api#9]
On Octopus Deploy UI, we can deploy to a single machine on a specified environment. The use case is   the following: when we create a new machine in an environment (for scaling out the web application), we do not want to do a full deploy on the environment, only just on this single machine (initial deploy for this machine).

Is it possible with the current API?

**Comment by Dalmirog** [comment]
Hi,

Thanks for reaching out. I've copied this question over help.octopusdeploy.com as that is the place where users usually go when they need help with Octopus. Please try to ask there the next time, even for questions such as these about the API.

Link to answer: http://help.octopusdeploy.com/discussions/questions/4351

Thanks!
