### ISSUE TITLE
[Feature Request] - Update single variable on a release

### ISSUE THREAD

**Issue by wiredsource** [OctopusDeploy/OctopusDeploy-Api#93]
Hi guys,

I would like to be able to update a single variable instead of the entire snapshot. 
In my case a drop down of a prompted variable is being updated by a teamcity build step triggered by another "Create Octopus Release" build configuration. The drop down contains a releases and therefore is in need for the latest one as well.
I don't like to update all variable as I don't necessarily know the impact. I'm only interested in updating this single variable...

Could this feature request be beneficial? 

best regards

**Comment by harrisonmeister** [comment]
Hi @wiredsource Thanks for getting in touch!

We have a UserVoice site where you can submit feature requests - https://octopusdeploy.uservoice.com/

It's worth browsing the existing requests in case someone else already raised the idea, and if they have you can upvote the request and add any additional use-cases or comments.

Thanks again!
